# Generated by Django 3.0.6 on 2020-05-08 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hojasroot', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='community',
            old_name='name',
            new_name='communityID',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='community',
            new_name='communityID',
        ),
    ]
